name: Build and deploy static frontend to Azure Web App - GenesysListening

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read  # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4  # Checks out your repository

      - name: Upload static frontend files
        run: |
          echo "Preparing static files for deployment"
          # This assumes your static files (HTML, JS, CSS) are in the root folder or public directory
          mkdir -p ./dist
          cp -r ./path-to-your-static-files/* ./dist/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: static-frontend
          path: ./dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: static-frontend

      - name: 'Deploy static files to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'GenesysListening'  # Your Azure Web App name
          slot-name: 'Production'  # Change this if you're using deployment slots
          package: ./dist  # The directory containing your static files
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_EE027099C3AA4223A8A542CBA2772409 }}
