name: Deploy static files to Azure Web App - GenesysListening

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Log in to Azure using App Registration credentials
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: '{"clientId": "${{ secrets.AZURE_CLIENT_ID }}", "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}", "tenantId": "${{ secrets.AZURE_TENANT_ID }}"}'

      # Step 3: Deploy to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'GenesysListening'  # Your Azure Web App name
          slot-name: 'Production'  # You can change to a different slot if needed
          package: .  # Path to the directory you want to deploy (root of the repo)
