name: Deploy static files to Azure Web App - GenesysListening

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up Azure CLI
      - name: Set up Azure CLI
        uses: azure/setup-azurecli@v1

      # Step 3: Log in to Azure using the App Registration credentials
      - name: Azure CLI login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      # Step 4: Deploy the static files to Azure Web App
      - name: Deploy to Azure Web App
        run: |
          az webapp deploy --resource-group <your-resource-group> --name GenesysListening --src-path . --type static
