name: Build and deploy Node.js app to Azure Web App - GenesysListening

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - uses: actions/checkout@v4  # Checkout your repo

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'GenesysListening'  # Replace with your Azure Web App name
          slot-name: 'Production'
          package: ./  # Deploy the root of your repo (static files)
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}  # Make sure you have the publish profile secret in GitHub
